---
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  tags: install

- name: Add specified repository into sources list using specified filename
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2
  tags: install

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: install

- name: Enable MongoDB service
  systemd: name=mongod enabled=yes
  tags: install
